### ISSUE TITLE
Compilation Error: Invalid Expression Term '[' in BaseEngine.cs

### ISSUE THREAD

**Issue by Kateles** [sharivan/XSharp#2]
### Description

I encountered a compilation error when trying to build the project. The error messages are as follows:

D:\XSharp\XSharp\Engine\BaseEngine.cs(853,25,853,26): error CS1525: Invalid expression term '['
D:\XSharp\XSharp\Engine\BaseEngine.cs(853,26,853,27): error CS0443: Syntax error, value expected
D:\XSharp\XSharp\Engine\BaseEngine.cs(854,27,854,28): error CS1525: Invalid expression term '['
D:\XSharp\XSharp\Engine\BaseEngine.cs(854,28,854,29): error CS0443: Syntax error, value expected
...
...

### Steps to Reproduce

1. Clone the repository.
2. Open the project in Visual Studio 2022.
3. Build the project.

### Expected Behavior

The project should compile without errors.

### Actual Behavior

The compilation fails with the errors mentioned above.

### Code Snippet

Here is the relevant part of the code where the error occurs:

```csharp
protected virtual void Initialize(dynamic initializers)
{
    RNG = new RNG();

    Entities = new EntityFactory();
    aliveEntities = [];
    spawnedEntities = [];
    removedEntities = [];
...
Environment
OS: Windows 11
IDE: Visual Studio 2022
.NET SDK: .NET 7.0
Additional Context
I have verified that all dependencies are installed correctly. Other members of the project seem to compile it successfully, so I suspect there might be some additional context or setup that I'm missing.

Any help or guidance on how to resolve this issue would be greatly appreciated. Thank you!

**Comment by Kateles** [comment]
I upgraded VS2022 to the latest 17.10.1 version and it compiled successfully. Thanks so much for your help

**Comment by sharivan** [comment]
Your welcome.
